exam7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('accounts.urls')),
]

webapp/urls.py
# from django.urls import path
#
# from webapp.views import PollView, PollDetailView, PollCreate, PollUpdate, PollDelete, ChoiceUpdate, \
#     ChoiceDelete, AnswerView, Answer, AnswerGo, ChoiceCreate1, AnswerDetailView
#
from django.urls import path

from webapp.views import ProductsView, ProductDetaillView, ProductCreate, ProductUpdate, ProductDelete, ReviewView, \
    ReviewDetaillView, ReviewCreate, ReviewUpdate, DeleteReview

app_name = 'webapp'
urlpatterns = [
    path('', ProductsView.as_view(), name='ProductsView'),
    path('product/<int:pk>', ProductDetaillView.as_view(), name='ProductDetaillView'),
#     # path('poll/<int:pk>/', PollDetailView1.as_view(), name='PollDetailView1'),
    path('create/', ProductCreate.as_view(), name='ProductCreate'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='ProductUpdate'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='ProductDelete'),
    path('review/', ReviewView.as_view(), name='ReviewView'),
    path('review/<int:pk>', ReviewDetaillView.as_view(), name='ReviewDetaillView'),
    path('review/create', ReviewCreate.as_view(), name='ReviewCreate'),
#     path('poll/<int:pk>/choice/add', ChoiceCreate1.as_view(), name='ChoiceCreate1'),
    path('review/<int:pk>/update/', ReviewUpdate.as_view(), name='ReviewUpdate'),
    path('review/<int:pk>/delete/', DeleteReview.as_view(), name='DeleteReview'),
#     path('answer/', AnswerView.as_view(), name='AnswerView'),
#     path('answer/<int:pk>', AnswerGo.as_view(), name='AnswerGo'),
#     path('answer/<int:pk>/detail', AnswerDetailView.as_view(), name='AnswerDetailView'),
#
#
#
#
#
#
#
]

webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

CHOICE = [('food', 'Еда'), ('milk', 'Молоко'), ('bred', 'Хлеб')]


# Create your models here
class Product(models.Model):
    name = models.TextField(max_length=20, verbose_name='Имя')
    category = models.TextField(choices=CHOICE)
    description = models.TextField(max_length=2000, verbose_name='Описание', null=True, blank=True)
    img = models.ImageField(upload_to='avatars', null=True, blank=True, verbose_name='Аватар')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        db_table = "Product"
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='review',
                               verbose_name='Пользователь')
    product = models.ForeignKey('webapp.Product',related_name='review', on_delete=models.CASCADE,
                             verbose_name='Продукт')
    text = models.TextField(max_length=2000,verbose_name='Текст отзыва')
    score = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    mod = models.BooleanField(null=True,blank=True,default=False,verbose_name='Модерирование')
    created_ad = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_ad = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return f'{self.author}'

    class Meta:
        db_table = "Review"
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

webapp/forms.py
from django import forms
#
# from webapp.models import Poll, Choice
#
#
from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

#
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['product','text','score']

webapp/views.py
#
# from django.shortcuts import get_object_or_404, redirect
# from django.urls import reverse, reverse_lazy
# from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
#
# from webapp.forms import PollForm, ChoiceForm
# from webapp.models import Poll, Choice, Answer
#
#
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm, ReviewForm
from webapp.models import Product, Review


class ProductsView(ListView):
    model = Product
    template_name = 'for_product/index.html'
    context_object_name = 'products'
    paginate_by = 5



    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        products=[]
        object_list=Product.objects.all()
        for product in object_list:
            total = 0
            review = product.review.filter(mod=1)
            for i in review:
                total+=i.score
            avg = total/len(review)
            product.avg = avg
            products.append(product)
        context['products']=products
        return context

#
class ProductDetaillView(DetailView):
    model = Product
    template_name = 'for_product/view.html'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        total = 0
        pk = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=pk)
        review = product.review.filter(mod=1)
        for i in review:
            total+=i.score
        avg = total/len(review)
        context['avg']=avg
        return context




class ProductCreate(PermissionRequiredMixin,CreateView):
    template_name = 'for_product/create.html'
    model = Product
    form_class = ProductForm
    permission_required = 'webapp.add_product'

    def get_success_url(self):
        return reverse('webapp:ProductDetaillView', kwargs={'pk': self.object.pk})
#
class ProductUpdate(PermissionRequiredMixin,UpdateView):
    template_name = 'for_product/update.html'
    model = Product
    form_class = ProductForm
    permission_required = 'webapp.change_product'



    def get_success_url(self):
        return reverse('webapp:ProductDetaillView', kwargs={'pk': self.object.pk})
#
class ProductDelete(PermissionRequiredMixin,DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'for_product/delete.html'
    success_url = reverse_lazy('webapp:ProductsView')
    permission_required = 'webapp.delete_product'
#


class ReviewView(ListView):
    model = Review
    template_name = 'for_review/view.html'
    context_object_name = 'review'





class ReviewDetaillView(DetailView):
    model = Review
    template_name = 'for_review/detailview.html'
    context_object_name = 'review'





class ReviewCreate(CreateView):
    template_name = 'for_review/create.html'
    form_class = ReviewForm


    def form_valid(self, form):
        author = self.request.user
        form.instance.author = author
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:ReviewDetaillView', kwargs={'pk': self.object.pk})
#
class ReviewUpdate(PermissionRequiredMixin, UpdateView):
    template_name = 'for_review/update.html'
    model = Review
    form_class = ReviewForm
    permission_required = 'webapp.change_review'

    def has_permission(self):
        return super().has_permission() and self.request.user == self.get_object().review.author

    def form_valid(self, form):
        if  self.request.user.is_superuser:
            self.object = form.save()
        else:
            self.object = form.save()
            self.object.mod = False
            self.object.save()
        return super().form_valid(form)




    def get_success_url(self):
        return reverse('webapp:ReviewDetaillView', kwargs={'pk': self.object.pk})
#
class DeleteReview(PermissionRequiredMixin, DeleteView):
    model = Review
    context_object_name = 'review'
    template_name = 'for_review/delete.html'
    success_url = reverse_lazy('webapp:ReviewView')
    permission_required = 'webapp.delete_review'

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().review.author.all()
#
#

#
#
#
#
#
#
#

webapp/templates/for_product/create.html
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'webapp:ProductCreate' %}" method="POST">
{%  include 'partial/form.html' with button='Create'%}



        </form>
{% endblock %}

webapp/templates/for_product/delete.html
{%  extends 'base.html' %}
{% block content %}

    <p>Вы уверенны, что хотите удалить {{ poll.question }}</p>
    <form action="" method="POST">
    {%  csrf_token %}
        <input name="Yes" type="submit" value="Да"/>
        <input name="No" type="submit" value="Нет"/>
    </form>
{%  endblock %}

webapp/templates/for_product/index.html
{% extends 'base.html' %}
{% block content %}
{% for product in products %}


    <div class="card" style="width: 24rem;">
  <div class="card-body">
    <h5 class="card-title">Название:
        <a href="{% url 'webapp:ProductDetaillView' product.pk %}">{{ product.name }}</a></h5>

        <p>Средний балл: {{ product.avg }}</p>



{% if perms.webapp.change_product %}
<a href="{% url 'webapp:ProductUpdate' product.pk  %}">Редактировать </a>
      {% endif %}
    <br>
  {% if perms.webapp.delete_product %}
      <a href="{% url 'webapp:ProductDelete' product.pk %}">Удалить </a>
{% endif %}
  </div>
</div>

{% endfor %}

{% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}


{% endblock %}

webapp/templates/for_product/view.html
{%  extends 'base.html' %}

{%  block content %}
<div class="container">
<i>Name:</i> <b>{{ product }}</b>
    <br>
    <i>Category: </i><b>{{ product.category }}</b>
    <br>
    <i>Description: </i><b>{{ product.description }}</b>
    <br>
    <i>Img: </i><b>{{ product.img}}</b>
    <br>
    <i>Средний балл: </i><b>{{ avg}}</b>
    <br>
{% if perms.webapp.change_product %}
    <a href="{% url 'webapp:ProductUpdate' product.pk  %}">Редактировать </a>
    {% endif %}
    <br>
{% if perms.webapp.delete_product %}
    <a href="{% url 'webapp:ProductDelete' product.pk %}">Удалить </a>

{% endif %}



</div>
{%  endblock %}

webapp/templates/for_product/view1.html
{%  extends 'base.html' %}

{%  block content %}
<div class="container">
TEST

        <br>


    <a href="{% url 'PollDelete' poll.pk %}">Удалить </a>
    <br>
{#    <a href="{% url 'SoftDeleteProject' project.pk %}">Мягкое удаление</a>#}



</div>
{%  endblock %}