accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import register_view, UsersView, UserDetailView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'
urlpatterns = [
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/create/', register_view, name='register_view'),
    path('accounts/users/', UsersView.as_view(), name='UsersView'),
    path('accounts/user/<int:pk>', UserDetailView.as_view(), name='UserDetailView'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='UserChangeView'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
]

exam7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('accounts.urls')),
]

webapp/urls.py
# from django.urls import path
#
# from webapp.views import PollView, PollDetailView, PollCreate, PollUpdate, PollDelete, ChoiceUpdate, \
#     ChoiceDelete, AnswerView, Answer, AnswerGo, ChoiceCreate1, AnswerDetailView
#
from django.urls import path

from webapp.views import ProductsView, ProductDetaillView, ProductCreate, ProductUpdate, ProductDelete, ReviewView, \
    ReviewDetaillView, ReviewCreate, ReviewUpdate, DeleteReview

app_name = 'webapp'
urlpatterns = [
    path('', ProductsView.as_view(), name='ProductsView'),
    path('product/<int:pk>', ProductDetaillView.as_view(), name='ProductDetaillView'),
#     # path('poll/<int:pk>/', PollDetailView1.as_view(), name='PollDetailView1'),
    path('create/', ProductCreate.as_view(), name='ProductCreate'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='ProductUpdate'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='ProductDelete'),
    path('review/', ReviewView.as_view(), name='ReviewView'),
    path('review/<int:pk>', ReviewDetaillView.as_view(), name='ReviewDetaillView'),
    path('review/create', ReviewCreate.as_view(), name='ReviewCreate'),
#     path('poll/<int:pk>/choice/add', ChoiceCreate1.as_view(), name='ChoiceCreate1'),
    path('review/<int:pk>/update/', ReviewUpdate.as_view(), name='ReviewUpdate'),
    path('review/<int:pk>/delete/', DeleteReview.as_view(), name='DeleteReview'),
#     path('answer/', AnswerView.as_view(), name='AnswerView'),
#     path('answer/<int:pk>', AnswerGo.as_view(), name='AnswerGo'),
#     path('answer/<int:pk>/detail', AnswerDetailView.as_view(), name='AnswerDetailView'),
#
#
#
#
#
#
#
]

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

class Profile(models.Model):
    avatar =models.ImageField(upload_to='avatars',null=True,blank=True,verbose_name='Аватар')
    git=models.URLField(max_length=100,blank=True,null=True,verbose_name='Ссылка')
    about = models.TextField(max_length=2000,null=True,blank=True,verbose_name='О себе')
    user =models.OneToOneField(get_user_model(),on_delete=models.CASCADE,related_name='profile',verbose_name='Пользователь')

accounts/forms.py
from django import forms
from django.contrib.auth import login, get_user_model
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.shortcuts import redirect

from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(max_length=200, required=True, validators=[validate_email])
    # first_name = forms.CharField(max_length=20, required=False)
    # last_name = forms.CharField(max_length=20, required=False)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']
        field_classes = {'username': UsernameField}

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        if not first_name and not last_name:
            self.add_error("first_name", "Заполните имя или фамилию")
            self.add_error("last_name", "Заполните имя или фамилию")


    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

accounts/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.contrib.auth import login as auth_login, login, get_user_model, update_session_auth_hash
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.generic import ListView, DetailView, UpdateView

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm
from accounts.models import Profile


class LoginView(LoginView):
    template_name = "registration/login.html"
    post_redirect = None


    def get(self, request, *args, **kwargs):
        self.object = None
        post_redirect = request.META.get('HTTP_REFERER')
        print(self.object,post_redirect)
        return super().get(request, *args, **kwargs)
#
    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.post_redirect)
#
#
#     def post(self, request, *args, **kwargs):
#         """Logout may be done via POST."""
#         self.object, self.redirect_url = self.get( request, *args, **kwargs)
#         print(self.redirect_url)
#         return self.object, self.redirect_url
#     #
#     #
#     # def get_redirect_url(self):
#     #     """Return the user-originating redirect URL if it's safe."""
#     #     x,redirect_url = self.post()
#     #     print(self.request)
#     #     redirect_to = redirect_url
#     #     print(redirect_to)
#     #     url_is_safe = url_has_allowed_host_and_scheme(
#     #         url=redirect_to,
#     #         allowed_hosts=self.get_success_url_allowed_hosts(),
#     #         require_https=self.request.is_secure(),
#     #     )
#     #     return HttpResponseRedirect(self.request.META.get('HTTP_REFERER')) if url_is_safe else ""
#     if post:
#         def get_success_url(self):
#             x, redirect_url = self.post()
#             print(self.request)
#             redirect_to = redirect_url
#             print(self.request.META.get('HTTP_REFERER','/'))
#             return HttpResponseRedirect(redirect_to)
#

def register_view(request, *args, **kwargs):

    if request.method == 'POST':
        try:
            form = MyUserCreationForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect('webapp:ProductsView')
        except: ValidationError
    else:
        form = MyUserCreationForm()
        return render(request, 'user_create.html', context={'form': form})
    # return redirect('webapp:ProductsView')


class UsersView(PermissionRequiredMixin, ListView):
    template_name = 'usersall.html'
    model = get_user_model()
    context_object_name = 'users'
    permission_required = 'webapp.view_user'

    def has_permission(self):
        """
        Override this method to customize the way permissions are checked.
        """
        return self.request.user.groups.filter(name__in=('Project Manager','Team Lead',)).exists()


class UserDetailView(DetailView):
    template_name = 'user.html'
    model = get_user_model()
    context_object_name = 'user'





class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'


    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)


    def form_valid(self, form, profile_form):
        if self.request.user:
            response = super().form_valid(form)
            profile_form.save()
            return response
        else:
            HttpResponseRedirect(self.get_success_url())


    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)


    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)


    def get_success_url(self):
        return reverse('accounts:UserDetailView', kwargs={'pk': self.object.pk})

class UserPasswordChangeView(PasswordChangeView):

    template_name = 'registration/password_change_form.html'

    def get_success_url(self):
        return reverse('accounts:UserDetailView', kwargs={'pk': self.request.user.pk})

accounts/templates/user.html
{% extends 'base.html' %}

{% block content %}
    <p>Имя пользователя: {{ user.username }}</p>
    <p>Имя: {{ request.user.first_name}}</p>
    <p>Почта: {{ user.email }}</p>
    <h2 class="text-center clear">Отзывы:</h2>
{%  for review in user.review.all %}
    <a href="{% url 'webapp:ReviewDetaillView' review.pk %}">{{ Review }}</a>

    {% endfor %}
    <li><a href="{% url 'accounts:UserChangeView' user.pk %}">Редактировать</a></li>
    <li><a href="{% url 'accounts:password_change'  %}">Смена пароля</a></li>
{% endblock %}

password_change

accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}
{% block menu_links %}
    <li><a href="{% url "accounts:UserDetailView" user.pk %}">Назад</a></li>
    <li><a href="#">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'accounts:UserChangeView' user.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True button='Изменить' %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

accounts/templates/user_create.html
{% extends 'base.html' %}


{% block content %}
    <h1>Регистрация</h1>
    <form action="" method="post">
    {% include 'partial/form.html' with form_method='post' button="Зарегистрироваться" %}
    </form>
{% endblock %}

accounts/templates/usersall.html
{% extends 'base.html' %}
{% block content %}
    {% for user in users %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Название:

                    <a href="{% url 'accounts:UserDetailView' user.id %} ">{{ user }}</a></h5>

{#                {% if perms.webapp.view_user  %}#}
{#                <a href="{% url 'webapp:UpdateProject' project.pk %}" class="card-link">Update</a>#}
{#                <a href="{% url 'webapp:DeleteProject' project.pk %}" class="card-link">Delete</a>#}
{#                <a href="{% url 'webapp:SoftDeleteProject' project.pk %}" class="card-link">SoftDelete</a>#}
{#                {% endif %}#}
            </div>
        </div>
    {% endfor %}
    {% if  request.user.project.all%}
    {% for project in request.user.project.all %}
        {% include 'partial/project_list.html' %}
    {% endfor %}
    {% endif %}

    {% if is_paginated %}
        {% include "partial/pagination.html" %}
    {% endif %}
{% endblock %}